### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harisdev-netizen**

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
I see you updated your Introduction. Please resolve merge conflicts.

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
You removed your introduction!

**Comment by harisdev-netizen** [comment]
> You removed your introduction!

Yes, I will add new in a while.

**Comment by KendallDoesCoding** [comment]
So should I merge this?

**Comment by harisdev-netizen** [comment]
> So should I merge this?

Yes. Sure.

**Comment by KendallDoesCoding** [comment]
> > So should I merge this?
> 
> Yes. Sure.

why you want to remove your introduction tho, i'll close this or you update your intro in this PR only, then will merge.

**Comment by harisdev-netizen** [comment]
> > > So should I merge this?
> > 
> > 
> > Yes. Sure.
> 
> why you want to remove your introduction tho, i'll close this or you update your intro in this PR only, then will merge.

Okay let me add my introduction.

**Pull request closed without merging**
