### PR TITLE
Beautified the intro page.

### PR DESCRIPTION
**Pull request by majeed69**
The information is looking so congested so i added || (VERTICAL BARS) in between the intro, so it will be readable and more clear!

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
I was considering doing this a long time back, but the issue is, it doesn't look too great on the README.md, but it looks great of the website.

What we can do is, make a NEW branch, where a github action will automatically add the | | to the README.md of that single branch, and that branch is hosted/deployed on the website.

What do y'all think @The-Lively-Developers-Community/maintainers ?

**Review by SandeepUrankar — APPROVED** [review]
Looks good.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Not sure if this is 100% needed.
Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).

**Comment by KendallDoesCoding** [comment]
> Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).

Can you make a branch where you add a markdown table and we see how github pages deploys the website?
@Panquesito7

**Comment by Panquesito7** [comment]
> > Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).
> 
> Can you make a branch where you add a markdown table and we see how github pages deploys the website? @Panquesito7

It'd be best to create an issue so that everyone can discuss about it and work on it as well. 🙂

**Comment by KendallDoesCoding** [comment]
> > > Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).
> > 
> > 
> > Can you make a branch where you add a markdown table and we see how github pages deploys the website? @Panquesito7
> 
> It'd be best to create an issue so that everyone can discuss about it and work on it as well. slightly_smiling_face

Discussion or Issue?

**Comment by Panquesito7** [comment]
> > > > Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).
> > > 
> > > 
> > > Can you make a branch where you add a markdown table and we see how github pages deploys the website? @Panquesito7
> > 
> > 
> > It'd be best to create an issue so that everyone can discuss about it and work on it as well. slightly_smiling_face
> 
> Discussion or Issue?

Issue would be best for this, IMO.

**Comment by KendallDoesCoding** [comment]
> > > > > Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).
> > > > 
> > > > 
> > > > Can you make a branch where you add a markdown table and we see how github pages deploys the website? @Panquesito7
> > > 
> > > 
> > > It'd be best to create an issue so that everyone can discuss about it and work on it as well. slightly_smiling_face
> > 
> > 
> > Discussion or Issue?
> 
> Issue would be best for this, IMO.

#40

**Pull request closed without merging**
